# 本番用のymlファイル、使うかどうかは不明

version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: my-root-pass
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: user-pass
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
  
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend-container
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    environment:
      # <データベースの種類>://<ユーザー名>:<パスワード>@<ホスト名>:<ポート番号>/<データベース名>
      DATABASE_URL: mysql://user:user-pass@mysql:3306/mydb
    depends_on:
      - mysql

  frontend:
    build:
      context: .
      target: runner  # 本番時はrunnerステージを使用
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
    command: npm start  # 本番モードで実行


volumes:
  mysql-data: