version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: my-root-pass
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: user-pass
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
  
  backend:
    build:
      context: .
      dockerfile: Dockerfiles/backend/Dockerfile
    container_name: backend-container
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app/backend
    environment:
      # <データベースの種類>://<ユーザー名>:<パスワード>@<ホスト名>:<ポート番号>/<データベース名>
      DATABASE_URL: mysql://user:user-pass@mysql:3306/mydb
    depends_on:
      - mysql

  frontend:
    build:
      context: .
      dockerfile: Dockerfiles/frontend/Dockerfile
      target: dev
    container_name: frontend-container
    volumes:
      - ./frontend:/app/frontend
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development


volumes:
  mysql-data: